name: GitHub Actions Demo
on: [push]
jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Deploy to Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        region: us-east-1
        image: 'gcr.io/gcp-hackathon-338316/nextjs'
        service: 'nextjs'